-- 功能：补齐销售订单、销售出库、销售退货快照字段并初始化对账基础结构
-- 创建时间：2026-05-10
-- 创建人：GPT-5.4
-- MIGRATION_ID: 007_sales_order_and_reconciliation_bootstrap
-- MIGRATION_APPLIED: applied_20260516T142223

BEGIN;

ALTER TABLE sales_order
    ADD COLUMN IF NOT EXISTS customer_name varchar(200),
    ADD COLUMN IF NOT EXISTS contract_no varchar(50),
    ADD COLUMN IF NOT EXISTS payment_method varchar(50),
    ADD COLUMN IF NOT EXISTS receiver_name varchar(100),
    ADD COLUMN IF NOT EXISTS receiver_phone varchar(20),
    ADD COLUMN IF NOT EXISTS receiver_address varchar(500);

ALTER TABLE sales_order_item
    ADD COLUMN IF NOT EXISTS material_code varchar(30),
    ADD COLUMN IF NOT EXISTS material_name varchar(200),
    ADD COLUMN IF NOT EXISTS unit varchar(20);

ALTER TABLE return_order
    ADD COLUMN IF NOT EXISTS customer_code varchar(20),
    ADD COLUMN IF NOT EXISTS customer_name varchar(200);

ALTER TABLE stock_out
    ADD COLUMN IF NOT EXISTS customer_code varchar(20),
    ADD COLUMN IF NOT EXISTS customer_name varchar(200);

COMMENT ON COLUMN sales_order.customer_name IS '客户名称快照';
COMMENT ON COLUMN sales_order.contract_no IS '合同编号';
COMMENT ON COLUMN sales_order.payment_method IS '付款方式';
COMMENT ON COLUMN sales_order.receiver_name IS '收货联系人';
COMMENT ON COLUMN sales_order.receiver_phone IS '收货联系电话';
COMMENT ON COLUMN sales_order.receiver_address IS '收货地址';
COMMENT ON COLUMN sales_order_item.material_code IS '物料编码快照';
COMMENT ON COLUMN sales_order_item.material_name IS '物料名称快照';
COMMENT ON COLUMN sales_order_item.unit IS '单位快照';
COMMENT ON COLUMN return_order.customer_code IS '客户编码快照';
COMMENT ON COLUMN return_order.customer_name IS '客户名称快照';
COMMENT ON COLUMN stock_out.customer_code IS '客户编码快照';
COMMENT ON COLUMN stock_out.customer_name IS '客户名称快照';

CREATE INDEX IF NOT EXISTS idx_sales_order_customer_name
    ON sales_order (customer_name)
    WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_return_order_customer_code
    ON return_order (customer_code)
    WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_stock_out_customer_code
    ON stock_out (customer_code)
    WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS reconciliation_order (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reconcile_no varchar(20) NOT NULL,
    reconcile_type varchar(20) NOT NULL,
    partner_type varchar(20) NOT NULL,
    partner_code varchar(20) NOT NULL,
    partner_name varchar(200) NOT NULL,
    start_date date NOT NULL,
    end_date date NOT NULL,
    status varchar(20) NOT NULL DEFAULT 'draft',
    total_amount numeric(18,2) NOT NULL DEFAULT 0,
    remark text,
    created_by bigint,
    created_at timestamptz NOT NULL DEFAULT NOW(),
    updated_by bigint,
    updated_at timestamptz NOT NULL DEFAULT NOW(),
    deleted_at timestamptz
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_reconciliation_order_no
    ON reconciliation_order (reconcile_no)
    WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_reconciliation_order_type_partner
    ON reconciliation_order (reconcile_type, partner_code)
    WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_reconciliation_order_status
    ON reconciliation_order (status)
    WHERE deleted_at IS NULL;

COMMENT ON TABLE reconciliation_order IS '对账单';
COMMENT ON COLUMN reconciliation_order.reconcile_no IS '对账单号';
COMMENT ON COLUMN reconciliation_order.reconcile_type IS '对账类型：purchase/sales';
COMMENT ON COLUMN reconciliation_order.partner_type IS '往来类型：supplier/customer';
COMMENT ON COLUMN reconciliation_order.partner_code IS '往来编码';
COMMENT ON COLUMN reconciliation_order.partner_name IS '往来名称快照';
COMMENT ON COLUMN reconciliation_order.start_date IS '对账开始日期';
COMMENT ON COLUMN reconciliation_order.end_date IS '对账结束日期';
COMMENT ON COLUMN reconciliation_order.status IS '状态：draft/confirmed/closed';
COMMENT ON COLUMN reconciliation_order.total_amount IS '净额合计';
COMMENT ON COLUMN reconciliation_order.remark IS '备注';

CREATE TABLE IF NOT EXISTS reconciliation_order_item (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reconciliation_id bigint NOT NULL,
    source_doc_type varchar(50) NOT NULL,
    source_doc_id bigint NOT NULL,
    source_doc_no varchar(50) NOT NULL,
    doc_date date NOT NULL,
    material_id bigint,
    material_code varchar(30),
    material_name varchar(200),
    quantity numeric(18,3) NOT NULL DEFAULT 0,
    unit varchar(20),
    unit_price numeric(18,2) NOT NULL DEFAULT 0,
    amount numeric(18,2) NOT NULL DEFAULT 0,
    direction varchar(20) NOT NULL DEFAULT 'positive',
    remark text,
    created_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_reconciliation_order_item_parent
    ON reconciliation_order_item (reconciliation_id);

CREATE INDEX IF NOT EXISTS idx_reconciliation_order_item_source
    ON reconciliation_order_item (source_doc_type, source_doc_id);

COMMENT ON TABLE reconciliation_order_item IS '对账单明细';
COMMENT ON COLUMN reconciliation_order_item.reconciliation_id IS '对账单ID';
COMMENT ON COLUMN reconciliation_order_item.source_doc_type IS '来源单据类型';
COMMENT ON COLUMN reconciliation_order_item.source_doc_id IS '来源单据ID';
COMMENT ON COLUMN reconciliation_order_item.source_doc_no IS '来源单据号';
COMMENT ON COLUMN reconciliation_order_item.doc_date IS '业务日期';
COMMENT ON COLUMN reconciliation_order_item.material_id IS '物料ID';
COMMENT ON COLUMN reconciliation_order_item.material_code IS '物料编码快照';
COMMENT ON COLUMN reconciliation_order_item.material_name IS '物料名称快照';
COMMENT ON COLUMN reconciliation_order_item.quantity IS '数量';
COMMENT ON COLUMN reconciliation_order_item.unit IS '单位';
COMMENT ON COLUMN reconciliation_order_item.unit_price IS '单价';
COMMENT ON COLUMN reconciliation_order_item.amount IS '金额';
COMMENT ON COLUMN reconciliation_order_item.direction IS '方向：positive/negative';
COMMENT ON COLUMN reconciliation_order_item.remark IS '备注';

DO $$
DECLARE
    v_sales_menu_id bigint;
    v_reconcile_menu_id bigint;
    v_admin_role_id bigint;
BEGIN
    IF to_regclass('public.sys_permission') IS NOT NULL THEN
        SELECT id INTO v_sales_menu_id
        FROM sys_permission
        WHERE perm_code = 'sales'
        LIMIT 1;

        IF NOT EXISTS (
            SELECT 1 FROM sys_permission WHERE perm_code = 'sales:return'
        ) THEN
            INSERT INTO sys_permission (
                parent_id, perm_code, perm_name, perm_type, path, icon, sort_order, status, created_at, updated_at
            ) VALUES (
                COALESCE(v_sales_menu_id, 0), 'sales:return', '销售退货单', 'menu', '/sales/returns', 'RefreshCw', 3, 'enabled', NOW(), NOW()
            );
        ELSE
            UPDATE sys_permission
            SET perm_name = '销售退货单',
                path = '/sales/returns',
                updated_at = NOW()
            WHERE perm_code = 'sales:return';
        END IF;

        IF NOT EXISTS (
            SELECT 1 FROM sys_permission WHERE perm_code = 'reconciliation'
        ) THEN
            INSERT INTO sys_permission (
                parent_id, perm_code, perm_name, perm_type, path, icon, sort_order, status, created_at, updated_at
            ) VALUES (
                0, 'reconciliation', '对账管理', 'menu', '/reconciliation', 'Wallet', 6, 'enabled', NOW(), NOW()
            );
        END IF;

        SELECT id INTO v_reconcile_menu_id
        FROM sys_permission
        WHERE perm_code = 'reconciliation'
        LIMIT 1;

        IF NOT EXISTS (
            SELECT 1 FROM sys_permission WHERE perm_code = 'reconciliation:purchase'
        ) THEN
            INSERT INTO sys_permission (
                parent_id, perm_code, perm_name, perm_type, path, icon, sort_order, status, created_at, updated_at
            ) VALUES (
                COALESCE(v_reconcile_menu_id, 0), 'reconciliation:purchase', '采购对账', 'menu', '/reconciliation/purchase', 'FileSpreadsheet', 1, 'enabled', NOW(), NOW()
            );
        END IF;

        IF NOT EXISTS (
            SELECT 1 FROM sys_permission WHERE perm_code = 'reconciliation:sales'
        ) THEN
            INSERT INTO sys_permission (
                parent_id, perm_code, perm_name, perm_type, path, icon, sort_order, status, created_at, updated_at
            ) VALUES (
                COALESCE(v_reconcile_menu_id, 0), 'reconciliation:sales', '销售对账', 'menu', '/reconciliation/sales', 'ReceiptText', 2, 'enabled', NOW(), NOW()
            );
        END IF;
    END IF;

    IF to_regclass('public.sys_role') IS NOT NULL
        AND to_regclass('public.sys_role_permission') IS NOT NULL
        AND to_regclass('public.sys_permission') IS NOT NULL THEN
        SELECT id INTO v_admin_role_id
        FROM sys_role
        WHERE role_code = 'admin'
        LIMIT 1;

        IF v_admin_role_id IS NOT NULL THEN
            INSERT INTO sys_role_permission (role_id, permission_id, created_at)
            SELECT v_admin_role_id, p.id, NOW()
            FROM sys_permission p
            WHERE p.perm_code IN ('sales:order', 'sales:return', 'reconciliation', 'reconciliation:purchase', 'reconciliation:sales')
              AND NOT EXISTS (
                  SELECT 1
                  FROM sys_role_permission rp
                  WHERE rp.role_id = v_admin_role_id
                    AND rp.permission_id = p.id
              );
        END IF;
    END IF;
END $$;

COMMIT;
