-- MIGRATION_ID: 016_production_order_auto_from_consumption
-- MIGRATION_APPLIED: pending

BEGIN;

ALTER TABLE consumption_order
	ADD COLUMN IF NOT EXISTS produced_material_id BIGINT NULL,
	ADD COLUMN IF NOT EXISTS produced_quantity NUMERIC(18, 3) NULL,
	ADD COLUMN IF NOT EXISTS produced_warehouse_id BIGINT NULL;

ALTER TABLE consumption_order
	DROP CONSTRAINT IF EXISTS consumption_order_production_fields_ck;

ALTER TABLE consumption_order
	ADD CONSTRAINT consumption_order_production_fields_ck
	CHECK (
		(produced_material_id IS NULL AND produced_quantity IS NULL AND produced_warehouse_id IS NULL)
		OR
		(produced_material_id IS NOT NULL AND produced_quantity IS NOT NULL AND produced_quantity > 0 AND produced_warehouse_id IS NOT NULL)
	);

COMMENT ON COLUMN consumption_order.produced_material_id IS '自动生产入库：成品物料ID（可空；设置后会在领料出库确认时自动生成生产单+成品入库）';
COMMENT ON COLUMN consumption_order.produced_quantity IS '自动生产入库：成品数量（可空；与 produced_material_id/produced_warehouse_id 绑定）';
COMMENT ON COLUMN consumption_order.produced_warehouse_id IS '自动生产入库：成品入库仓库ID（可空；与 produced_material_id/produced_quantity 绑定）';

CREATE TABLE IF NOT EXISTS production_order (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	production_no VARCHAR(20) NOT NULL UNIQUE,
	consumption_order_id BIGINT NOT NULL UNIQUE REFERENCES consumption_order(id),
	stock_out_id BIGINT NOT NULL REFERENCES stock_out(id),
	stock_in_id BIGINT NOT NULL REFERENCES stock_in(id),
	produced_material_id BIGINT NOT NULL REFERENCES material(id),
	produced_warehouse_id BIGINT NOT NULL REFERENCES warehouse(id),
	produced_quantity NUMERIC(18, 3) NOT NULL CHECK (produced_quantity > 0),
	produced_unit_cost NUMERIC(18, 3) NOT NULL DEFAULT 0,
	status VARCHAR(20) NOT NULL DEFAULT 'completed',
	remark TEXT NULL,
	created_by BIGINT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT NOW(),
	updated_by BIGINT NULL,
	updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE production_order IS '生产单（系统自动生成：领料出库确认后生成成品入库并记录映射关系）';
COMMENT ON COLUMN production_order.production_no IS '生产单号：PR + 年月日 + 序号（复用 fn_generate_serial_no）';
COMMENT ON COLUMN production_order.consumption_order_id IS '来源领料单ID（1:1）';
COMMENT ON COLUMN production_order.stock_out_id IS '关联领料出库单ID';
COMMENT ON COLUMN production_order.stock_in_id IS '关联成品入库单ID（自动确认）';
COMMENT ON COLUMN production_order.produced_material_id IS '成品物料ID';
COMMENT ON COLUMN production_order.produced_warehouse_id IS '成品入库仓库ID';
COMMENT ON COLUMN production_order.produced_quantity IS '成品数量';
COMMENT ON COLUMN production_order.produced_unit_cost IS '

/数量分摊）';
COMMENT ON COLUMN production_order.status IS '状态：completed（目前仅自动完成态）';

CREATE TABLE IF NOT EXISTS production_return_order (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	return_no VARCHAR(20) NOT NULL UNIQUE,
	production_order_id BIGINT NOT NULL REFERENCES production_order(id),
	stock_out_id BIGINT NULL REFERENCES stock_out(id),
	returned_quantity NUMERIC(18, 3) NOT NULL CHECK (returned_quantity > 0),
	status VARCHAR(20) NOT NULL DEFAULT 'created',
	remark TEXT NULL,
	created_by BIGINT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT NOW(),
	updated_by BIGINT NULL,
	updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE production_return_order IS '生产退货单（预留：成品从仓库退回/报废等导致成品库存减少的记录；目前仅展示）';
COMMENT ON COLUMN production_return_order.return_no IS '生产退货单号：PRR + 年月日 + 序号（复用 fn_generate_serial_no）';
COMMENT ON COLUMN production_return_order.production_order_id IS '关联生产单ID';
COMMENT ON COLUMN production_return_order.stock_out_id IS '关联出库单ID（可空；预留）';
COMMENT ON COLUMN production_return_order.returned_quantity IS '退回数量（成品）';
COMMENT ON COLUMN production_return_order.status IS '状态：created/confirmed/cancelled（预留）';

DROP VIEW IF EXISTS v_production_order_list;
CREATE VIEW v_production_order_list AS
SELECT
	po.id,
	po.production_no,
	po.status,
	po.consumption_order_id,
	co.order_no AS consumption_order_no,
	po.stock_out_id,
	so.stock_out_no,
	po.stock_in_id,
	si.stock_in_no,
	po.produced_material_id,
	m.material_code AS produced_material_code,
	m.material_name AS produced_material_name,
	po.produced_warehouse_id,
	w.warehouse_code AS produced_warehouse_code,
	w.warehouse_name AS produced_warehouse_name,
	po.produced_quantity,
	po.produced_unit_cost,
	po.remark,
	po.created_at,
	po.updated_at
FROM production_order po
LEFT JOIN consumption_order co ON co.id = po.consumption_order_id
LEFT JOIN stock_out so ON so.id = po.stock_out_id
LEFT JOIN stock_in si ON si.id = po.stock_in_id
LEFT JOIN material m ON m.id = po.produced_material_id
LEFT JOIN warehouse w ON w.id = po.produced_warehouse_id;

DROP VIEW IF EXISTS v_production_return_order_list;
CREATE VIEW v_production_return_order_list AS
SELECT
	pro.id,
	pro.return_no,
	pro.status,
	pro.production_order_id,
	po.production_no,
	po.consumption_order_id,
	co.order_no AS consumption_order_no,
	pro.stock_out_id,
	so.stock_out_no,
	po.produced_material_id,
	m.material_code AS produced_material_code,
	m.material_name AS produced_material_name,
	po.produced_warehouse_id,
	w.warehouse_code AS produced_warehouse_code,
	w.warehouse_name AS produced_warehouse_name,
	pro.returned_quantity,
	pro.remark,
	pro.created_at,
	pro.updated_at
FROM production_return_order pro
LEFT JOIN production_order po ON po.id = pro.production_order_id
LEFT JOIN consumption_order co ON co.id = po.consumption_order_id
LEFT JOIN stock_out so ON so.id = pro.stock_out_id
LEFT JOIN material m ON m.id = po.produced_material_id
LEFT JOIN warehouse w ON w.id = po.produced_warehouse_id AND w.deleted_at IS NULL;

CREATE OR REPLACE PROCEDURE sp_generate_production_from_consumption(
	IN p_consumption_order_id BIGINT,
	IN p_stock_out_id BIGINT,
	IN p_operator_id BIGINT
)
LANGUAGE plpgsql
AS $procedure$
DECLARE
	v_co RECORD;
	v_wh RECORD;
	v_mat RECORD;
	v_exists BIGINT;
	v_total_cost NUMERIC(18, 3);
	v_unit_cost NUMERIC(18, 3);
	v_stock_in_id BIGINT;
	v_stock_in_no VARCHAR(20);
	v_production_no VARCHAR(20);
	v_production_id BIGINT;
BEGIN
	IF COALESCE(p_operator_id, 0) = 0 THEN
		RETURN;
	END IF;

	SELECT
		co.id,
		co.order_no,
		co.order_date,
		co.status,
		co.produced_material_id,
		co.produced_quantity,
		co.produced_warehouse_id
	INTO v_co
	FROM consumption_order co
	WHERE co.id = p_consumption_order_id
	  AND co.deleted_at IS NULL
	FOR UPDATE;

	IF v_co IS NULL THEN
		RETURN;
	END IF;

	IF v_co.produced_material_id IS NULL OR v_co.produced_quantity IS NULL OR v_co.produced_warehouse_id IS NULL THEN
		RETURN;
	END IF;

	SELECT id INTO v_exists
	FROM production_order
	WHERE consumption_order_id = p_consumption_order_id
	LIMIT 1;

	IF v_exists IS NOT NULL THEN
		RETURN;
	END IF;

	SELECT id, warehouse_code, warehouse_name INTO v_wh
	FROM warehouse
	WHERE id = v_co.produced_warehouse_id AND deleted_at IS NULL;

	IF v_wh IS NULL THEN
		RAISE EXCEPTION '成品入库仓库不存在 [warehouse_id=%]', v_co.produced_warehouse_id;
	END IF;

	SELECT id, material_code, material_name, COALESCE(NULLIF(TRIM(unit), ''), '件') AS unit, COALESCE(is_code, FALSE) AS is_code
	INTO v_mat
	FROM material
	WHERE id = v_co.produced_material_id AND deleted_at IS NULL;

	IF v_mat IS NULL THEN
		RAISE EXCEPTION '成品物料不存在 [material_id=%]', v_co.produced_material_id;
	END IF;

	IF v_mat.is_code THEN
		RAISE EXCEPTION '成品物料为有编码物料，暂不支持自动生产入库（需要生成/选择编码）[%-%]',
			v_mat.material_code, v_mat.material_name;
	END IF;

	SELECT COALESCE(SUM(coi.quantity * COALESCE(inv.unit_cost, 0)), 0)
	INTO v_total_cost
	FROM consumption_order_item coi
	LEFT JOIN inventory inv ON inv.id = coi.inventory_id
	WHERE coi.order_id = p_consumption_order_id;

	IF v_co.produced_quantity <= 0 THEN
		RAISE EXCEPTION '成品数量必须 > 0';
	END IF;

	v_unit_cost := v_total_cost / v_co.produced_quantity;
	v_stock_in_no := fn_generate_serial_no('SI');

	INSERT INTO stock_in (
		stock_in_no,
		warehouse_id, warehouse_code,
		stock_in_date,
		stock_in_status,
		stock_in_type,
		remark,
		created_by, created_at, updated_by, updated_at
	) VALUES (
		v_stock_in_no,
		v_wh.id, v_wh.warehouse_code,
		COALESCE(v_co.order_date, CURRENT_DATE),
		'preparing',
		'production',
		'生产单自动生成（领料出库确认后）',
		p_operator_id, NOW(), p_operator_id, NOW()
	)
	RETURNING id INTO v_stock_in_id;

	INSERT INTO stock_in_item (
		stock_in_id,
		material_id,
		arrived_quantity,
		accepted_quantity,
		unit,
		unit_cost,
		custom_attributes,
		created_at
	) VALUES (
		v_stock_in_id,
		v_mat.id,
		v_co.produced_quantity,
		v_co.produced_quantity,
		v_mat.unit,
		v_unit_cost,
		'[]'::jsonb,
		NOW()
	);

	CALL sp_confirm_stock_in(v_stock_in_id, p_operator_id);

	v_production_no := fn_generate_serial_no('PR');

	INSERT INTO production_order (
		production_no,
		consumption_order_id,
		stock_out_id,
		stock_in_id,
		produced_material_id,
		produced_warehouse_id,
		produced_quantity,
		produced_unit_cost,
		status,
		remark,
		created_by,
		updated_by
	) VALUES (
		v_production_no,
		p_consumption_order_id,
		p_stock_out_id,
		v_stock_in_id,
		v_mat.id,
		v_wh.id,
		v_co.produced_quantity,
		v_unit_cost,
		'completed',
		'由领料出库确认自动生成',
		p_operator_id,
		p_operator_id
	)
	RETURNING id INTO v_production_id;
END;
$procedure$;

CREATE OR REPLACE FUNCTION trg_stock_out_after_confirm_generate_production()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $function$
BEGIN
	IF TG_OP = 'UPDATE'
		AND NEW.status = 'confirmed'
		AND COALESCE(OLD.status, '') <> 'confirmed'
		AND NEW.ref_doc_type = 'consumption_order'
		AND COALESCE(NEW.ref_doc_id, 0) <> 0
		AND COALESCE(NEW.updated_by, 0) <> 0
	THEN
		CALL sp_generate_production_from_consumption(NEW.ref_doc_id, NEW.id, NEW.updated_by);
	END IF;
	RETURN NEW;
END;
$function$;

DROP TRIGGER IF EXISTS stock_out_after_confirm_generate_production ON stock_out;
CREATE TRIGGER stock_out_after_confirm_generate_production
AFTER UPDATE OF status ON stock_out
FOR EACH ROW
EXECUTE FUNCTION trg_stock_out_after_confirm_generate_production();

COMMIT;

