-- MIGRATION_ID: 022_reconciliation_payment_collection_sources
-- MIGRATION_APPLIED: pending
-- 功能：完善采购/销售对账来源，支持退货抵充、票款区分、实收实付差额

BEGIN;

CREATE TABLE IF NOT EXISTS fund_payment (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    statement_no varchar(30) NOT NULL UNIQUE,
    supplier_id bigint NOT NULL,
    payer_id bigint NOT NULL,
    statement_date date NOT NULL,
    payment_amount numeric(18,2) DEFAULT 0,
    discount_amount numeric(18,2) DEFAULT 0,
    advance_amount numeric(18,2) DEFAULT 0,
    settlement_method varchar(50),
    settlement_account varchar(50),
    settlement_no varchar(50),
    remark text,
    status varchar(20) NOT NULL DEFAULT 'draft',
    created_by bigint,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_by bigint,
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz
);

CREATE TABLE IF NOT EXISTS fund_payment_item (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    statement_id bigint NOT NULL,
    source_order_id bigint NOT NULL,
    source_order_no varchar(30) NOT NULL,
    business_type varchar(30) NOT NULL,
    order_date date NOT NULL,
    order_amount numeric(18,2) DEFAULT 0,
    verified_amount numeric(18,2) DEFAULT 0,
    unverified_amount numeric(18,2) DEFAULT 0,
    current_verify_amount numeric(18,2) DEFAULT 0,
    custom_tax_amount numeric(18,2) DEFAULT 0,
    remark text,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS fund_collection (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    statement_no varchar(30) NOT NULL UNIQUE,
    customer_id bigint NOT NULL,
    payee_id bigint NOT NULL,
    statement_date date NOT NULL,
    collection_amount numeric(18,2) DEFAULT 0,
    discount_amount numeric(18,2) DEFAULT 0,
    advance_amount numeric(18,2) DEFAULT 0,
    settlement_method varchar(50),
    settlement_account varchar(50),
    settlement_no varchar(50),
    remark text,
    status varchar(20) NOT NULL DEFAULT 'draft',
    created_by bigint,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_by bigint,
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz
);

CREATE TABLE IF NOT EXISTS fund_collection_item (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    statement_id bigint NOT NULL,
    source_order_id bigint NOT NULL,
    source_order_no varchar(30) NOT NULL,
    business_type varchar(30) NOT NULL,
    order_date date NOT NULL,
    order_amount numeric(18,2) DEFAULT 0,
    verified_amount numeric(18,2) DEFAULT 0,
    unverified_amount numeric(18,2) DEFAULT 0,
    current_verify_amount numeric(18,2) DEFAULT 0,
    custom_tax_amount numeric(18,2) DEFAULT 0,
    remark text,
    created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE purchase_order ADD COLUMN IF NOT EXISTS verified_amount numeric(18,2) DEFAULT 0;
ALTER TABLE sales_order ADD COLUMN IF NOT EXISTS verified_amount numeric(18,2) DEFAULT 0;

ALTER TABLE fund_payment
    ADD COLUMN IF NOT EXISTS bill_type varchar(20) NOT NULL DEFAULT 'cash',
    ADD COLUMN IF NOT EXISTS invoice_amount numeric(18,2) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS actual_amount numeric(18,2) NOT NULL DEFAULT 0;

ALTER TABLE fund_collection
    ADD COLUMN IF NOT EXISTS bill_type varchar(20) NOT NULL DEFAULT 'cash',
    ADD COLUMN IF NOT EXISTS invoice_amount numeric(18,2) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS actual_amount numeric(18,2) NOT NULL DEFAULT 0;

ALTER TABLE fund_payment_item
    ADD COLUMN IF NOT EXISTS source_doc_type varchar(50) NOT NULL DEFAULT 'purchase_order';

ALTER TABLE fund_collection_item
    ADD COLUMN IF NOT EXISTS source_doc_type varchar(50) NOT NULL DEFAULT 'sales_order';

UPDATE fund_payment
SET actual_amount = payment_amount
WHERE COALESCE(actual_amount, 0) = 0
  AND COALESCE(payment_amount, 0) <> 0;

UPDATE fund_collection
SET actual_amount = collection_amount
WHERE COALESCE(actual_amount, 0) = 0
  AND COALESCE(collection_amount, 0) <> 0;

COMMENT ON COLUMN fund_payment.bill_type IS '票款类型：cash-款项，invoice-票据，offset-抵充';
COMMENT ON COLUMN fund_payment.invoice_amount IS '票据金额';
COMMENT ON COLUMN fund_payment.actual_amount IS '实际付款金额';
COMMENT ON COLUMN fund_payment_item.source_doc_type IS '来源单据类型：purchase_order/purchase_return';
COMMENT ON COLUMN fund_collection.bill_type IS '票款类型：cash-款项，invoice-票据，offset-抵充';
COMMENT ON COLUMN fund_collection.invoice_amount IS '票据金额';
COMMENT ON COLUMN fund_collection.actual_amount IS '实际收款金额';
COMMENT ON COLUMN fund_collection_item.source_doc_type IS '来源单据类型：sales_order/sales_return';

DROP VIEW IF EXISTS v_fund_payment_list;
CREATE OR REPLACE VIEW v_fund_payment_list AS
SELECT
    p.id, p.statement_no, p.supplier_id,
    COALESCE(s.supplier_name, '') AS supplier_name,
    COALESCE(s.supplier_code, '') AS supplier_code,
    p.payer_id, COALESCE(u.real_name, u.username, '') AS payer_name,
    p.statement_date,
    COALESCE(p.bill_type, 'cash') AS bill_type,
    COALESCE(p.payment_amount, 0) AS payment_amount,
    COALESCE(p.invoice_amount, 0) AS invoice_amount,
    COALESCE(p.actual_amount, 0) AS actual_amount,
    COALESCE(p.discount_amount, 0) AS discount_amount,
    COALESCE(p.advance_amount, 0) AS advance_amount,
    COALESCE(p.settlement_method, '') AS settlement_method,
    COALESCE(p.settlement_account, '') AS settlement_account,
    COALESCE(p.settlement_no, '') AS settlement_no,
    COALESCE(p.remark, '') AS remark,
    p.status, p.created_at, p.updated_at, p.deleted_at,
    COALESCE(p.payment_amount, 0) - COALESCE(p.actual_amount, 0) AS difference_amount
FROM fund_payment p
LEFT JOIN supplier s ON p.supplier_id = s.id
LEFT JOIN sys_user u ON p.payer_id = u.id
WHERE p.deleted_at IS NULL;

DROP VIEW IF EXISTS v_fund_collection_list;
CREATE OR REPLACE VIEW v_fund_collection_list AS
SELECT
    c.id, c.statement_no, c.customer_id,
    COALESCE(cu.customer_name, '') AS customer_name,
    COALESCE(cu.customer_code, '') AS customer_code,
    c.payee_id, COALESCE(u.real_name, u.username, '') AS payee_name,
    c.statement_date,
    COALESCE(c.bill_type, 'cash') AS bill_type,
    COALESCE(c.collection_amount, 0) AS collection_amount,
    COALESCE(c.invoice_amount, 0) AS invoice_amount,
    COALESCE(c.actual_amount, 0) AS actual_amount,
    COALESCE(c.discount_amount, 0) AS discount_amount,
    COALESCE(c.advance_amount, 0) AS advance_amount,
    COALESCE(c.settlement_method, '') AS settlement_method,
    COALESCE(c.settlement_account, '') AS settlement_account,
    COALESCE(c.settlement_no, '') AS settlement_no,
    COALESCE(c.remark, '') AS remark,
    c.status, c.created_at, c.updated_at, c.deleted_at,
    COALESCE(c.collection_amount, 0) - COALESCE(c.actual_amount, 0) AS difference_amount
FROM fund_collection c
LEFT JOIN customer cu ON c.customer_id = cu.id
LEFT JOIN sys_user u ON c.payee_id = u.id
WHERE c.deleted_at IS NULL;

DROP VIEW IF EXISTS v_fund_payment_source;
CREATE OR REPLACE VIEW v_fund_payment_source AS
WITH payment_verified AS (
    SELECT
        fpi.source_doc_type,
        fpi.source_order_id,
        SUM(COALESCE(fpi.current_verify_amount, 0)) AS verified_amount
    FROM fund_payment_item fpi
    JOIN fund_payment fp ON fp.id = fpi.statement_id
    WHERE fp.deleted_at IS NULL
      AND fp.status = 'completed'
    GROUP BY fpi.source_doc_type, fpi.source_order_id
),
purchase_sources AS (
    SELECT
        'purchase_order'::varchar(50) AS source_doc_type,
        po.id AS source_order_id,
        po.order_no AS source_order_no,
        '采购订单'::varchar(30) AS business_type,
        po.order_date,
        po.supplier_id,
        po.supplier_code,
        COALESCE(s.supplier_name, '') AS supplier_name,
        COALESCE(po.total_amount, 0)::numeric(18,2) AS order_amount,
        COALESCE(pv.verified_amount, 0)::numeric(18,2) AS verified_amount
    FROM purchase_order po
    LEFT JOIN supplier s ON s.supplier_code = po.supplier_code AND s.deleted_at IS NULL
    LEFT JOIN payment_verified pv ON pv.source_doc_type = 'purchase_order' AND pv.source_order_id = po.id
    WHERE po.deleted_at IS NULL
      AND po.order_status NOT IN ('draft', 'cancelled')

    UNION ALL

    SELECT
        'purchase_return'::varchar(50) AS source_doc_type,
        ro.id AS source_order_id,
        ro.return_no AS source_order_no,
        '采购退货抵充'::varchar(30) AS business_type,
        ro.return_date AS order_date,
        s.id AS supplier_id,
        COALESCE(ro.supplier_code, '') AS supplier_code,
        COALESCE(s.supplier_name, '') AS supplier_name,
        (-COALESCE((
            SELECT SUM(roi.quantity * COALESCE(inv.unit_cost, 0))
            FROM return_order_item roi
            LEFT JOIN inventory inv ON inv.id = roi.inventory_id
            WHERE roi.return_id = ro.id
        ), 0))::numeric(18,2) AS order_amount,
        COALESCE(pv.verified_amount, 0)::numeric(18,2) AS verified_amount
    FROM return_order ro
    LEFT JOIN supplier s ON s.supplier_code = ro.supplier_code AND s.deleted_at IS NULL
    LEFT JOIN payment_verified pv ON pv.source_doc_type = 'purchase_return' AND pv.source_order_id = ro.id
    WHERE ro.deleted_at IS NULL
      AND ro.return_type = 'purchase_return'
      AND ro.return_status NOT IN ('draft', 'closed', 'cancelled')
)
SELECT
    source_doc_type, source_order_id, source_order_no, business_type, order_date,
    supplier_id, supplier_code, supplier_name,
    order_amount,
    verified_amount,
    (order_amount - verified_amount)::numeric(18,2) AS unverified_amount,
    CASE
        WHEN ABS(order_amount - verified_amount) < 0.005 THEN 'completed'
        WHEN ABS(verified_amount) > 0 THEN 'partial'
        ELSE 'pending'
    END AS verify_status
FROM purchase_sources;

DROP VIEW IF EXISTS v_fund_collection_source;
CREATE OR REPLACE VIEW v_fund_collection_source AS
WITH collection_verified AS (
    SELECT
        fci.source_doc_type,
        fci.source_order_id,
        SUM(COALESCE(fci.current_verify_amount, 0)) AS verified_amount
    FROM fund_collection_item fci
    JOIN fund_collection fc ON fc.id = fci.statement_id
    WHERE fc.deleted_at IS NULL
      AND fc.status = 'completed'
    GROUP BY fci.source_doc_type, fci.source_order_id
),
sales_sources AS (
    SELECT
        'sales_order'::varchar(50) AS source_doc_type,
        so.id AS source_order_id,
        so.order_no AS source_order_no,
        '销售订单'::varchar(30) AS business_type,
        so.order_date,
        so.customer_id,
        so.customer_code,
        COALESCE(so.customer_name, c.customer_name, '') AS customer_name,
        COALESCE(so.total_amount, 0)::numeric(18,2) AS order_amount,
        COALESCE(cv.verified_amount, 0)::numeric(18,2) AS verified_amount
    FROM sales_order so
    LEFT JOIN customer c ON c.customer_code = so.customer_code AND c.deleted_at IS NULL
    LEFT JOIN collection_verified cv ON cv.source_doc_type = 'sales_order' AND cv.source_order_id = so.id
    WHERE so.deleted_at IS NULL
      AND so.order_status NOT IN ('draft', 'cancelled')

    UNION ALL

    SELECT
        'sales_return'::varchar(50) AS source_doc_type,
        ro.id AS source_order_id,
        ro.return_no AS source_order_no,
        '销售退货抵充'::varchar(30) AS business_type,
        ro.return_date AS order_date,
        c.id AS customer_id,
        COALESCE(ro.customer_code, '') AS customer_code,
        COALESCE(ro.customer_name, c.customer_name, '') AS customer_name,
        (-COALESCE((
            SELECT SUM(roi.quantity * COALESCE(soi.unit_price, inv.unit_cost, 0))
            FROM return_order_item roi
            LEFT JOIN sales_order ref_so ON ref_so.id = ro.ref_doc_id AND ro.ref_doc_type = 'sales_order'
            LEFT JOIN sales_order_item soi ON soi.order_id = ref_so.id AND soi.material_id = roi.material_id
            LEFT JOIN inventory inv ON inv.id = roi.inventory_id
            WHERE roi.return_id = ro.id
        ), 0))::numeric(18,2) AS order_amount,
        COALESCE(cv.verified_amount, 0)::numeric(18,2) AS verified_amount
    FROM return_order ro
    LEFT JOIN customer c ON c.customer_code = ro.customer_code AND c.deleted_at IS NULL
    LEFT JOIN collection_verified cv ON cv.source_doc_type = 'sales_return' AND cv.source_order_id = ro.id
    WHERE ro.deleted_at IS NULL
      AND ro.return_type = 'sales_return'
      AND ro.return_status NOT IN ('draft', 'closed', 'cancelled')
)
SELECT
    source_doc_type, source_order_id, source_order_no, business_type, order_date,
    customer_id, customer_code, customer_name,
    order_amount,
    verified_amount,
    (order_amount - verified_amount)::numeric(18,2) AS unverified_amount,
    CASE
        WHEN ABS(order_amount - verified_amount) < 0.005 THEN 'completed'
        WHEN ABS(verified_amount) > 0 THEN 'partial'
        ELSE 'pending'
    END AS verify_status
FROM sales_sources;

CREATE INDEX IF NOT EXISTS idx_fund_payment_item_source
    ON fund_payment_item (source_doc_type, source_order_id);

CREATE INDEX IF NOT EXISTS idx_fund_collection_item_source
    ON fund_collection_item (source_doc_type, source_order_id);

COMMIT;
