import os

def create_file(path, content):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w') as f:
        f.write(content.strip() + '\n')
    print(f"Created {path}")

# 1. SQL Migration
sql_content = """
BEGIN;

-- 采购付款单
CREATE TABLE IF NOT EXISTS fund_payment (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    statement_no varchar(30) NOT NULL UNIQUE,
    supplier_id bigint NOT NULL,
    payer_id bigint NOT NULL,
    statement_date date NOT NULL,
    payment_amount numeric(18,2) DEFAULT 0,
    discount_amount numeric(18,2) DEFAULT 0,
    advance_amount numeric(18,2) DEFAULT 0,
    settlement_method varchar(50),
    settlement_account varchar(50),
    settlement_no varchar(50),
    remark text,
    status varchar(20) NOT NULL DEFAULT 'draft',
    created_by bigint,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_by bigint,
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz
);

CREATE TABLE IF NOT EXISTS fund_payment_item (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    statement_id bigint NOT NULL,
    source_order_id bigint NOT NULL,
    source_order_no varchar(30) NOT NULL,
    business_type varchar(30) NOT NULL,
    order_date date NOT NULL,
    order_amount numeric(18,2) DEFAULT 0,
    verified_amount numeric(18,2) DEFAULT 0,
    unverified_amount numeric(18,2) DEFAULT 0,
    current_verify_amount numeric(18,2) DEFAULT 0,
    custom_tax_amount numeric(18,2) DEFAULT 0,
    remark text,
    created_at timestamptz NOT NULL DEFAULT now()
);

-- 销售收款单
CREATE TABLE IF NOT EXISTS fund_collection (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    statement_no varchar(30) NOT NULL UNIQUE,
    customer_id bigint NOT NULL,
    payee_id bigint NOT NULL,
    statement_date date NOT NULL,
    collection_amount numeric(18,2) DEFAULT 0,
    discount_amount numeric(18,2) DEFAULT 0,
    advance_amount numeric(18,2) DEFAULT 0,
    settlement_method varchar(50),
    settlement_account varchar(50),
    settlement_no varchar(50),
    remark text,
    status varchar(20) NOT NULL DEFAULT 'draft',
    created_by bigint,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_by bigint,
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz
);

CREATE TABLE IF NOT EXISTS fund_collection_item (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    statement_id bigint NOT NULL,
    source_order_id bigint NOT NULL,
    source_order_no varchar(30) NOT NULL,
    business_type varchar(30) NOT NULL,
    order_date date NOT NULL,
    order_amount numeric(18,2) DEFAULT 0,
    verified_amount numeric(18,2) DEFAULT 0,
    unverified_amount numeric(18,2) DEFAULT 0,
    current_verify_amount numeric(18,2) DEFAULT 0,
    custom_tax_amount numeric(18,2) DEFAULT 0,
    remark text,
    created_at timestamptz NOT NULL DEFAULT now()
);

-- 修改采销单表，增加已核销金额
ALTER TABLE purchase_order ADD COLUMN IF NOT EXISTS verified_amount numeric(18,2) DEFAULT 0;
ALTER TABLE sales_order ADD COLUMN IF NOT EXISTS verified_amount numeric(18,2) DEFAULT 0;

-- 增加视图
CREATE OR REPLACE VIEW v_fund_payment_list AS
SELECT 
    p.id, p.statement_no, p.supplier_id, s.supplier_name, s.supplier_code,
    p.payer_id, u.real_name AS payer_name, p.statement_date,
    p.payment_amount, p.discount_amount, p.advance_amount,
    p.settlement_method, p.settlement_account, p.settlement_no,
    p.remark, p.status, p.created_at, p.updated_at, p.deleted_at
FROM fund_payment p
LEFT JOIN supplier s ON p.supplier_id = s.id
LEFT JOIN sys_user u ON p.payer_id = u.id
WHERE p.deleted_at IS NULL;

CREATE OR REPLACE VIEW v_fund_collection_list AS
SELECT 
    c.id, c.statement_no, c.customer_id, cu.customer_name, cu.customer_code,
    c.payee_id, u.real_name AS payee_name, c.statement_date,
    c.collection_amount, c.discount_amount, c.advance_amount,
    c.settlement_method, c.settlement_account, c.settlement_no,
    c.remark, c.status, c.created_at, c.updated_at, c.deleted_at
FROM fund_collection c
LEFT JOIN customer cu ON c.customer_id = cu.id
LEFT JOIN sys_user u ON c.payee_id = u.id
WHERE c.deleted_at IS NULL;

COMMIT;
"""
create_file('sql/migrations/013_payment_and_collection.sql', sql_content)
